apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: transaction-engine
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - transaction-engine
  selector:
    matchLabels:
      app: transaction-engine
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_rollouts_pod_template_hash]
          targetLabel: rollout_hash
        - sourceLabels: [__meta_kubernetes_pod_label_app]
          targetLabel: app
