apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: transaction-engine-secrets
  namespace: transaction-engine
  labels:
    app.kubernetes.io/part-of: transaction-engine
    app.kubernetes.io/component: secrets-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: localstack-secrets-manager
    kind: ClusterSecretStore
  target:
    name: transaction-engine-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_CONNECTION_STRING
      remoteRef:
        key: yuno/transaction-engine/db-connection-string
    - secretKey: PROVIDER_API_KEY
      remoteRef:
        key: yuno/transaction-engine/provider-api-key
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: yuno/transaction-engine/encryption-key
