apiVersion: v1
kind: Secret
metadata:
  name: localstack-credentials
  namespace: secrets
  labels:
    app.kubernetes.io/part-of: transaction-engine
    app.kubernetes.io/component: secrets-management
type: Opaque
stringData:
  access-key-id: "test"
  secret-access-key: "test"
