apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: localstack-secrets-manager
  labels:
    app.kubernetes.io/part-of: transaction-engine
    app.kubernetes.io/component: secrets-management
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      additionalRoles: []
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-credentials
            namespace: secrets
            key: access-key-id
          secretAccessKeySecretRef:
            name: localstack-credentials
            namespace: secrets
            key: secret-access-key
