apiVersion: v1
kind: Service
metadata:
  name: transaction-engine
  namespace: transaction-engine
  labels:
    app: transaction-engine
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app: transaction-engine
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
