apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: transaction-engine-role
  namespace: transaction-engine
  labels:
    app.kubernetes.io/name: transaction-engine
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["transaction-engine-secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: transaction-engine-binding
  namespace: transaction-engine
  labels:
    app.kubernetes.io/name: transaction-engine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: transaction-engine-role
subjects:
  - kind: ServiceAccount
    name: transaction-engine
    namespace: transaction-engine
